# [unstable]
# build-std-features = ["compiler-builtins-mem"]
# build-std = ["core", "alloc", "compiler_builtins"]


# [build]
# target = "x86_64-mini_os.json"



# [target.'cfg(target_os = "none")']
# runner = "bootimage runner"



[build]
target = "x86_64-unknown-none"